#ifndef GLOBALS_H
#define GLOBALS_H

#define STYLESHEET  0
#define MAINWINDOW_MIN_WIDTH   800
#define MAINWINDOW_MIN_HEIGHT  500
#define MEMORYWINDOW_MIN_WIDTH 600
#define MEMORYWINDOW_MIN_HEIGHT 475
#define PERFORMANCEWINDOW_MIN_WIDTH 350
#define PERFORMANCEWINDOW_MIN_HEIGHT 250
#define TIMER_UPDATE 100
#define PLOT_XRANGE 5
#define PLOT_YRANGE 10

#endif // GLOBALS_H
